export const person = new Map()
    .set("firstName", "Anna")
    .set("lastName", "Vessereau")
    .set("job", "Développeuse JS FullStack")
    .set("age", "27")
    .set("address", "17 rue Ferdinand Buisson")
    .set("zipCode", "92110")
    .set("city", "Clichy")
    .set("phone", "06 73 85 56 35")
    .set("email", "anna.vessereau@gmail.com")
    .set("about", "Je suis une grande aventurière dans l'âme, j'aime les challenges et les défis, ce qui me pousse à dépasser mes limites! A la recherche de renouveau et ayant une bonne capacité d'adaptation, j'aime découvrir et apprendre de nouvelles choses afin de maintenir mon cerveau en éveil et pouvoir ainsi partager mes connaissances si nécessaire!")
    .set("experiences", [
        new Map()
            .set("date", "2015-2018")
            .set("title", "Conseillère de vente en maroquinerie")
            .set("location", "Michael Kors / BHV Marais, Galeries Lafayette"),
        new Map()
            .set("date", "2015")
            .set("title", "Conseillère de vente en parfumerie")
            .set("location", "Sephora / Levallois-Perret"),
        new Map()
            .set("date", "2015")
            .set("title", "Ambassadrice de Givenchy, Lancôme, Guerlain")
            .set("location", "Sephora, Marionnaud / Paris")
    ])
    .set("formations", [
        new Map()
            .set("date", "2015")
            .set("title", "Formation Anglais professionnel du Tourisme et TOEIC")
            .set("location", "CFC, Arles"),
        new Map()
            .set("date", "2014")
            .set("title", "Formation Anglais professionnel et TOEIC BUSINESS")
            .set("location", "Institut Greta, Avignon"),
        new Map()
            .set("date", "2013")
            .set("title", "Certificat de la réflexologie plantaire chinoise et massage Suédois")
            .set("location", "Etablissement de massages professionnels, Slovaquie")
    ])
    .set("hobbies", ["photos", "chats", "Netflix", "Disney", "Musique", "Chocolat"])